name: Fullstack CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install backend dependencies
      working-directory: backend
      run: npm install

    - name: Run backend tests (dummy)
      working-directory: backend
      run: echo "Backend tests placeholder"

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install

    - name: Build frontend (Angular)
      working-directory: frontend
      run: npm run build --if-present
